# Generated by Django 5.2.1 on 2025-05-14 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fname', models.CharField(max_length=100)),
                ('lname', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('services', models.CharField(choices=[('manual_therapy', 'Personalized Individual Therapy'), ('chronic_pain', 'Supportive Couples Counseling'), ('hand_therapy', 'Youth and Adolescent Counseling'), ('sports_therapy', 'Anxiety and Depression Support'), ('cupping_therapy', 'Stress and Anger Management'), ('laser_therapy', 'Mindfulness and Meditation Practices')], max_length=50)),
                ('date', models.DateField()),
            ],
        ),
    ]
