# Generated by Django 5.2.1 on 2025-05-21 04:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_contact_appointment_submitted_at'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('specialization', models.CharField(max_length=100)),
                ('license_number', models.CharField(max_length=50)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('clinic_address', models.TextField(blank=True, null=True)),
                ('education', models.CharField(blank=True, max_length=200, null=True)),
                ('availability', models.CharField(blank=True, max_length=100, null=True)),
                ('consultation_fee', models.CharField(blank=True, max_length=50, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=15)),
                ('dob', models.DateField(blank=True, null=True)),
                ('emergency_contact', models.CharField(blank=True, max_length=15, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('age', models.IntegerField(blank=True, null=True)),
                ('reason_concerns', models.TextField(blank=True, null=True)),
                ('concern_duration', models.CharField(blank=True, max_length=100, null=True)),
                ('reason_now', models.TextField(blank=True, null=True)),
                ('past_therapy', models.CharField(blank=True, max_length=10, null=True)),
                ('therapy_reason', models.TextField(blank=True, null=True)),
                ('past_diagnosis', models.TextField(blank=True, null=True)),
                ('hospitalization', models.TextField(blank=True, null=True)),
                ('current_medication', models.CharField(blank=True, max_length=10, null=True)),
                ('medication_list', models.TextField(blank=True, null=True)),
                ('medical_conditions', models.TextField(blank=True, null=True)),
                ('surgeries', models.TextField(blank=True, null=True)),
                ('substance_use', models.TextField(blank=True, null=True)),
                ('family_history', models.TextField(blank=True, null=True)),
                ('living_with', models.TextField(blank=True, null=True)),
                ('support_system', models.TextField(blank=True, null=True)),
                ('sleep', models.TextField(blank=True, null=True)),
                ('appetite', models.TextField(blank=True, null=True)),
                ('energy_concentration', models.TextField(blank=True, null=True)),
                ('life_changes', models.TextField(blank=True, null=True)),
                ('self_harm_thoughts', models.TextField(blank=True, null=True)),
                ('suicide_attempts', models.TextField(blank=True, null=True)),
                ('environment_safety', models.TextField(blank=True, null=True)),
                ('therapy_goals', models.TextField(blank=True, null=True)),
                ('consent_acknowledged', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
